openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API documentation project using OpenAPI and Swagger UI.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production Server
paths:
  /users:
    get:
      summary: Retrieve a list of users
      description: Fetches all registered users in the system.
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
